name: Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        vault-version: [1.3.10, 1.4.7, 1.5.7, 1.6.2]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        tests/scripts/install-consul.sh
        tests/scripts/install-vault.sh ${{ matrix.vault-version }} enterprise
        pip install -r requirements-dev.txt
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Lint with flake8
      run: flake8 . --count --exit-zero --statistics

    - name: Test with pytest
      run: pytest --cov=hvac tests/

    - name: Codecov - Process coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        verbose: true
